param(
  [switch]$NoPublish,
  [switch]$SkipInstall,
  [switch]$SkipCodeSigningValidation,
  [switch]$AllowDirty,
  [switch]$UseCurrentVersion,
  [string]$Branch = "main"
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Invoke-Native {
  param(
    [Parameter(Mandatory = $true)][string]$FilePath,
    [Parameter(ValueFromRemainingArguments = $true)][string[]]$Arguments
  )

  & $FilePath @Arguments
  if ($LASTEXITCODE -ne 0) {
    throw "$FilePath $($Arguments -join ' ') failed with exit code $LASTEXITCODE."
  }
}

function Invoke-Step {
  param(
    [Parameter(Mandatory = $true)][string]$Name,
    [Parameter(Mandatory = $true)][scriptblock]$ScriptBlock
  )

  Write-Host ""
  Write-Host "==> $Name"
  & $ScriptBlock
}

function Import-DotEnvLocal {
  $envPath = Join-Path (Get-Location) ".env.local"
  if (-not (Test-Path $envPath)) {
    return
  }

  Get-Content $envPath | ForEach-Object {
    $line = $_.Trim()
    if (-not $line -or $line.StartsWith("#") -or -not $line.Contains("=")) {
      return
    }

    $key, $value = $line.Split("=", 2)
    $key = $key.Trim()
    $value = $value.Trim().Trim('"').Trim("'")

    if ($key -and [string]::IsNullOrWhiteSpace([Environment]::GetEnvironmentVariable($key, "Process"))) {
      [Environment]::SetEnvironmentVariable($key, $value, "Process")
    }
  }
}

function Resolve-GitHubRepository {
  $remote = (& git remote get-url origin).Trim()
  if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($remote)) {
    throw "Could not resolve git remote origin."
  }

  $match = [regex]::Match($remote, "github\.com[:/](?<owner>[^/]+)/(?<repo>[^/.]+)(?:\.git)?/?$")
  if (-not $match.Success) {
    throw "Remote origin is not a GitHub repository URL: $remote"
  }

  return @{
    Owner = $match.Groups["owner"].Value
    Repo = $match.Groups["repo"].Value
  }
}

function Get-DirtyPaths {
  $status = & git status --porcelain
  if (-not $status) {
    return @()
  }

  return @(
    $status | ForEach-Object {
      $line = $_
      if ($line.Length -lt 4) {
        return
      }

      $path = $line.Substring(3).Trim()
      if ($path.Contains(" -> ")) {
        $path = $path.Split(" -> ", 2)[1]
      }

      $path.Replace("\", "/")
    }
  )
}

function Replace-ReadmeValue {
  param(
    [Parameter(Mandatory = $true)][string]$Text,
    [Parameter(Mandatory = $true)][string]$Pattern,
    [Parameter(Mandatory = $true)][scriptblock]$Replacement,
    [Parameter(Mandatory = $true)][string]$Name
  )

  $regex = [regex]::new($Pattern)
  if (-not $regex.IsMatch($Text)) {
    throw "README marker not found: $Name"
  }

  return $regex.Replace($Text, { param($match) & $Replacement $match }, 1)
}

function New-ReleaseBody {
  param(
    [Parameter(Mandatory = $true)][string]$DownloadUrl
  )

  $body = @"
**Download & Hinweise**

Nur die Datei "Apprenticeship-Reports-Setup.exe" herunterladen und ausführen.

- Die Dateien "latest.yml" und "*.exe.blockmap" sind für den Auto-Updater.
- "Source code (zip/tar.gz)" wird von GitHub automatisch erzeugt.

Direktdownload: $DownloadUrl

---

**Download & Notes**

Download and run only "Apprenticeship-Reports-Setup.exe".

- "latest.yml" and "*.exe.blockmap" are for the auto-updater.
- "Source code (zip/tar.gz)" is auto-generated by GitHub.

Direct download: $DownloadUrl
"@

  return $body.Trim()
}

function Resolve-NextPatchVersion {
  $currentVersion = (node -p "require('./package.json').version").Trim()
  $parts = $currentVersion.Split(".")

  if ($parts.Count -ne 3) {
    throw "Cannot bump non-standard version: $currentVersion"
  }

  $major = 0
  $minor = 0
  $patch = 0

  if (
    -not [int]::TryParse($parts[0], [ref]$major) -or
    -not [int]::TryParse($parts[1], [ref]$minor) -or
    -not [int]::TryParse($parts[2], [ref]$patch)
  ) {
    throw "Cannot bump non-numeric version: $currentVersion"
  }

  return "$major.$minor.$($patch + 1)"
}

$repoRoot = (& git rev-parse --show-toplevel).Trim()
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($repoRoot)) {
  throw "This script must be run inside a git repository."
}
Set-Location $repoRoot

$currentBranch = (& git rev-parse --abbrev-ref HEAD).Trim()
if ($currentBranch -ne $Branch) {
  throw "Release must run on '$Branch'. Current branch: '$currentBranch'."
}

Import-DotEnvLocal
if ([string]::IsNullOrWhiteSpace($env:GOOGLE_DRIVE_REQUIRED_SCOPES)) {
  $env:GOOGLE_DRIVE_REQUIRED_SCOPES = "https://www.googleapis.com/auth/drive.file"
}

if (-not $SkipInstall) {
  Invoke-Step "Install deps" {
    Invoke-Native npm ci
  }
}

if (-not $AllowDirty) {
  $dirtyPaths = @(Get-DirtyPaths)
  $allowedResumePaths = @("package.json", "package-lock.json", "README.md")
  $unexpectedDirtyPaths = @()

  if ($UseCurrentVersion) {
    $unexpectedDirtyPaths = @(
      $dirtyPaths | Where-Object { $allowedResumePaths -notcontains $_ }
    )
  } else {
    $unexpectedDirtyPaths = @($dirtyPaths)
  }

  if ($unexpectedDirtyPaths.Count -gt 0) {
    throw "Working tree is not clean. Commit or stash changes first, or pass -AllowDirty. Dirty paths: $($unexpectedDirtyPaths -join ', ')"
  }
}

Invoke-Step "Resolve release version" {
  git config user.name "github-actions[bot]"
  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

  $script:Version =
    if ($UseCurrentVersion) {
      (node -p "require('./package.json').version").Trim()
    } else {
      Resolve-NextPatchVersion
    }
  $script:Tag = "v$script:Version"
  Write-Host $script:Tag
}

Invoke-Step "Validate Google OAuth config" {
  if ([string]::IsNullOrWhiteSpace($env:GOOGLE_OAUTH_CLIENT_ID)) {
    throw "Missing GOOGLE_OAUTH_CLIENT_ID in environment or .env.local."
  }
}

Invoke-Step "Build app (webpack -> release/app)" {
  Invoke-Native npm run build
}

if (-not $SkipCodeSigningValidation) {
  Invoke-Step "Validate PFX password" {
    if ([string]::IsNullOrWhiteSpace($env:CSC_LINK) -or [string]::IsNullOrWhiteSpace($env:CSC_KEY_PASSWORD)) {
      throw "Missing CSC_LINK or CSC_KEY_PASSWORD in environment."
    }

    $tempDir = Join-Path ([System.IO.Path]::GetTempPath()) "apprenticeship-reports-release"
    New-Item -ItemType Directory -Path $tempDir -Force | Out-Null
    $pfx = Join-Path $tempDir "cs.pfx"
    $bytes = [Convert]::FromBase64String($env:CSC_LINK)
    [IO.File]::WriteAllBytes($pfx, $bytes)
    Invoke-Native certutil -p $env:CSC_KEY_PASSWORD -dump $pfx
  }
}

Invoke-Step "Package installer" {
  Write-Host "Packaging with version $script:Version"
  $env:CSC_LINK = $env:CSC_LINK
  $env:CSC_KEY_PASSWORD = $env:CSC_KEY_PASSWORD
  Invoke-Native npx electron-builder --win nsis --publish never "--config.extraMetadata.version=$script:Version"
}

if (-not $UseCurrentVersion) {
  Invoke-Step "Apply release version to package files" {
    Invoke-Native npm version $script:Version --no-git-tag-version
  }
}

$repository = Resolve-GitHubRepository
$download = "https://github.com/$($repository.Owner)/$($repository.Repo)/releases/latest/download/Apprenticeship-Reports-Setup.exe"

Invoke-Step "Update README.md with latest version and dates" {
  $dateDE = (Get-Date).ToString("dd.MM.yyyy")
  $content = Get-Content -Path README.md -Raw
  $content = Replace-ReadmeValue $content '\[Download for Windows\]\([^)]+\)' { param($match) "[Download for Windows]($download)" } "download link"
  $content = Replace-ReadmeValue $content '(- Version:\s*)`[^`]+`' { param($match) "$($match.Groups[1].Value)``$script:Tag``" } "version"
  $content = Replace-ReadmeValue $content '(- Ver[^\r\n]* am:\s*)`[^`]+`' { param($match) "$($match.Groups[1].Value)``$dateDE``" } "publish date"
  Set-Content -Path README.md -Value $content -Encoding UTF8 -NoNewline
}

Invoke-Step "Commit bumped version and create tag" {
  & git diff --quiet
  if ($LASTEXITCODE -ne 0) {
    Invoke-Native git add package.json package-lock.json README.md
    Invoke-Native git commit -m "ci(release): $script:Tag [skip ci]"
  }

  & git rev-parse -q --verify "refs/tags/$script:Tag" *> $null
  if ($LASTEXITCODE -eq 0) {
    throw "Tag already exists locally: $script:Tag"
  }

  Invoke-Native git tag $script:Tag
}

if ($NoPublish) {
  Write-Host ""
  Write-Host "Built local release without publishing."
  Write-Host "Tag created locally: $script:Tag"
  Write-Host "Assets: release/build"
  exit 0
}

Invoke-Step "Push release commit and tag" {
  Invoke-Native git push origin "HEAD:$Branch" $script:Tag
}

Invoke-Step "Create GitHub Release" {
  Invoke-Native gh auth status

  $bodyPath = Join-Path ([System.IO.Path]::GetTempPath()) "apprenticeship-release-body.md"
  Set-Content -Path $bodyPath -Value (New-ReleaseBody -DownloadUrl $download) -Encoding UTF8

  $assets = @(
    "release/build/Apprenticeship-Reports-Setup.exe",
    "release/build/latest.yml"
  )
  $blockmaps = @(Get-ChildItem -Path "release/build" -Filter "*.blockmap" -File)
  if ($blockmaps.Count -eq 0) {
    throw "Missing release asset: *.blockmap"
  }
  $assets += @($blockmaps | ForEach-Object { $_.FullName })

  foreach ($asset in $assets) {
    if (-not (Test-Path $asset)) {
      throw "Missing release asset: $asset"
    }
  }

  $retryCount = 5
  $success = $false

  for ($i = 1; $i -le $retryCount; $i++) {
    & gh release view $script:Tag *> $null
    if ($LASTEXITCODE -eq 0) {
      & gh release upload $script:Tag @assets --clobber
      if ($LASTEXITCODE -eq 0) {
        & gh release edit $script:Tag --title $script:Tag --notes-file $bodyPath --latest
        if ($LASTEXITCODE -eq 0) {
          $success = $true
          break
        }
      }
    } else {
      & gh release create $script:Tag @assets --title $script:Tag --notes-file $bodyPath --latest
      if ($LASTEXITCODE -eq 0) {
        $success = $true
        break
      }
    }

    Write-Host "GitHub CLI error. Retrying in 5 seconds ($i/$retryCount)..."
    Start-Sleep -Seconds 5
  }

  if (-not $success) {
    throw "GitHub Release could not be created after $retryCount attempts."
  }
}

Write-Host ""
Write-Host "Release published: $script:Tag"
